Add a flag var to check git is installed or not
Signed-off-by: Wonyeong Choi <ciwnyg0815@gmail.com>

diff --git a/scripts/get-helm-3 b/scripts/get-helm-3
--- a/scripts/get-helm-3
+++ b/scripts/get-helm-3
@@ -29,6 +29,7 @@ HAS_CURL="$(type "curl" &> /dev/null && echo true || echo false)"
 HAS_WGET="$(type "wget" &> /dev/null && echo true || echo false)"
 HAS_OPENSSL="$(type "openssl" &> /dev/null && echo true || echo false)"
 HAS_GPG="$(type "gpg" &> /dev/null && echo true || echo false)"
+HAS_GIT="$(type "git" &> /dev/null && echo true || echo false)"
 
 # initArch discovers the architecture for this system.
 initArch() {
@@ -96,6 +97,11 @@ verifySupported() {
       echo "Please set VERIFY_SIGNATURES=false or verify the signatures manually."
       exit 1
     fi
+  fi
+
+  if [ "${HAS_GIT}" != "true" ]; then
+    echo "Git is required for plugin install"
+    exit 1
   fi
 }
 
